label.disabled=\u6709\u52b9
label.executeAsynchronously=\u30eb\u30fc\u30eb\u3092\u30d0\u30c3\u30af\u30b0\u30e9\u30a6\u30f3\u30c9\u3067\u5b9f\u884c\u3057\u307e\u3059
label.applyToChildren=\u30eb\u30fc\u30eb\u304c\u30b5\u30d6\u30d5\u30a9\u30eb\u30c0\u306b\u3082\u9069\u7528\u3055\u308c\u307e\u3059
label.and=\u3059\u3079\u3066\u306e\u6761\u4ef6\u3092\u6e80\u305f\u3059\u5834\u5408
label.or=\u3044\u305a\u308c\u304b\u306e\u6761\u4ef6\u3092\u6e80\u305f\u3059\u5834\u5408
header.when=\u5b9f\u884c\u6761\u4ef6
header.if=\u6b21\u306e\u6761\u4ef6\u3092\u6e80\u305f\u3059\u5834\u5408
header.unless=\u6b21\u306e\u6761\u4ef6\u3092\u6e80\u305f\u3055\u306a\u3044\u5834\u5408
header.action=\u51e6\u7406\u306e\u5b9f\u884c
message.getRuleFailure=\u30eb\u30fc\u30eb\u306e\u60c5\u5831\u3092\u8aad\u307f\u8fbc\u3081\u307e\u305b\u3093\u3067\u3057\u305f
message.deletingRule=\u30eb\u30fc\u30eb\u3092\u524a\u9664\u3057\u3066\u3044\u307e\u3059...
message.confirm.delete.title=\u30eb\u30fc\u30eb\u306e\u524a\u9664
message.confirm.delete=\u3053\u306e\u30eb\u30fc\u30eb\u3092\u524a\u9664\u3057\u307e\u3059\u304b?
message.deletingRule-failure.title=\u30eb\u30fc\u30eb\u306f\u524a\u9664\u3055\u308c\u3066\u3044\u307e\u305b\u3093
message.deletingRule-failure.cause=\u3053\u306e\u30eb\u30fc\u30eb\u306f\u524a\u9664\u3067\u304d\u307e\u305b\u3093\u3067\u3057\u305f\u3002\u6b21\u306e\u8a73\u7d30\u3092\u30b3\u30d4\u30fc\u3057\u3066\u3001IT \u306b\u4f1d\u3048\u3066\u304f\u3060\u3055\u3044: \n When the DELETE call was made to {url} instead of the expected 200 OK return code we got: {error}.
